spring:
  application:
    name: GATEWAY-SERVICE
  config:
    import: configserver:http://localhost:2005  
  cloud:
    gateway:
      routes:
        - id: order-service
          uri : lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
          - name: CircuitBreaker
            args:
             name: callOrderFallback
             fallbackUri: forward:/falback/order

        - id: payment-service
          uri : lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
          filters:
          - name: CircuitBreaker
            args:
             name: callPaymentFallback
             fallbackUri: forward:/falback/payment
       

        - id: user-service
          uri : lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
          - name: CircuitBreaker
            args:
             name: callUserFallback
             fallbackUri: forward:/falback/user

#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/


server:
  port: 9090

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include : "gateway"